#:schema node_modules/wrangler/config-schema.json
name = "simple-atptoto-handles"
compatibility_date = "2024-10-22"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
[[d1_databases]]
binding = "DB"
database_name = "atproto-handle-db1"
database_id = "3af7b2ae-9656-4b9a-a1eb-3f1307a4ab04"
